// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show debugPrint, defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      debugPrint(
        'WARNING: The web Firebase instance is unconfigured. '
        'Testing should be shifted to a native mobile device target.',
      );
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfezu7wtc6gtZDE-RRkp3_VVYPRyqUZdw',
    appId: '1:459709003792:android:a87ed461a6229b07573295',
    messagingSenderId: '459709003792',
    projectId: 'vybin-firebase',
    storageBucket: 'vybin-firebase.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4SMYpbXJdMOCY-Nxk6ujk5YYbLaQiHPc',
    appId: '1:459709003792:ios:3bbab77787c89495573295',
    messagingSenderId: '459709003792',
    projectId: 'vybin-firebase',
    storageBucket: 'vybin-firebase.firebasestorage.app',
    iosBundleId: 'com.example.vybin.vybin',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'UNCONFIGURED_WEB_KEY',
    appId: '1:000000000000:web:unconfigured',
    messagingSenderId: '000000000000',
    projectId: 'vybin-unconfigured',
    authDomain: 'vybin-unconfigured.firebaseapp.com',
    storageBucket: 'vybin-unconfigured.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4SMYpbXJdMOCY-Nxk6ujk5YYbLaQiHPc',
    appId: '1:459709003792:ios:3bbab77787c89495573295',
    messagingSenderId: '459709003792',
    projectId: 'vybin-firebase',
    storageBucket: 'vybin-firebase.firebasestorage.app',
    iosBundleId: 'com.example.vybin.vybin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGSC2AxbLfxQr5Dq__nxvfFe7ctOB1AgI',
    appId: '1:459709003792:web:d149abbde3454802573295',
    messagingSenderId: '459709003792',
    projectId: 'vybin-firebase',
    authDomain: 'vybin-firebase.firebaseapp.com',
    storageBucket: 'vybin-firebase.firebasestorage.app',
  );
}
